import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";
import PlayerCount from "../components/PlayerCount";
import { useQuery } from "@tanstack/react-query";
import { fetchWhiteListCount } from "../utils/discord";
import PlayerCountv2 from "../components/PlayerCountv2";

type Props = {
  count: number
}
const Home: NextPage<Props> = (props) => {
  // const playerCount = useQuery(['player-count'], () => fetch('/api/whitelist').then(res => res.json()).then(res => res.count))
  return (
    <>
      <Head>
        <title>Passion Community</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-w-screen min-h-screen flex justify-center ">
        <PlayerCountv2 count={props.count} />
      </main>
    </>
  );
};

export default Home;


export async function getStaticProps() {
  const count = await fetchWhiteListCount();

  return {
    props: {
      count,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 30, // In seconds
  };
}